import { type NextPage } from 'next'
import Head from 'next/head'
import { useRouter } from 'next/router'
import BraneEditor from '../components/editor'
import { Layout } from '../components/layout/sidebar'
import { api } from '../utils/api'
import type { Descendant } from 'slate'

type ChangeHandler = React.ComponentProps<typeof BraneEditor>['onChange']

const NotePage: NextPage = () => {
  const router = useRouter()
  const { noteId } = router.query as { noteId: string }
  const { data: note } = api.note.getOne.useQuery({ id: noteId })

  const utils = api.useContext()
  const update = api.note.update.useMutation({
    async onMutate () {
      await utils.note.getAll.cancel()
      const prevData = utils.note.getAll.getData()
      return { prevData }
    },
    onError (_err, _newNote, ctx) {
      utils.note.getAll.setData(undefined, ctx?.prevData)
    },
    onSettled () {
      void utils.note.getAll.invalidate()
    }
  })

  const handleEditorChange: ChangeHandler = ({ blocks, title }) => {
    update.mutate({ id: noteId, title, content: JSON.stringify(blocks) })
  }

  return (
    <>
      <Head>
        <title>{note?.title ?? 'Loading...'} - Brane</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        {note && (
          <div className="p-4 max-w-5xl w-full">
            <BraneEditor
              value={{
                title: note.title,
                blocks: JSON.parse(note.content) as Descendant[]
              }}
              onChange={handleEditorChange}
            />
          </div>
        )}
        {!note && (
          <div className="p-4 max-w-5xl w-full">
            <p>death :(</p>
          </div>
        )}
      </Layout>
    </>
  )
}

export default NotePage
