import Head from 'next/head'
// import { api } from '../utils/api'
import { Layout } from '../components/layout/sidebar'
import type { NextPageWithLayout } from './_app'

const NotePage: NextPageWithLayout = () => {
  return (
    <>
      <Head>
        <title>Create New Note</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="p-4 max-w-5xl w-full">
      </div>
    </>
  )
}

NotePage.getLayout = function getLayout (page) {
  return (<Layout>{page}</Layout>)
}

export default NotePage
