import { type NextPage } from 'next'
import { signIn, useSession } from 'next-auth/react'
import Head from 'next/head'

const NotePage: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        hello world
      </main>
    </>
  )
}

const withAuth = (Component: NextPage) => {
  return ((props) => {
    const { status } = useSession({ required: true })

    if (status !== 'authenticated') {
      return (
        <>
          <p>Not signed in</p>
          <button onClick={() => void signIn()}>Sign in</button>
        </>
      )
    }

    return <Component {...props} />
  }) as React.FC
}

export default withAuth(NotePage)
