import { type NextPage } from 'next'
import Head from 'next/head'
import { useRouter } from 'next/router'
import { withAuth } from './_withAuth'
import { Layout } from './_layout'
import { api } from '../../utils/api'

const NotePage: NextPage = () => {
  const router = useRouter()
  const { noteId } = router.query
  const note = api.note.getOne.useQuery({ id: noteId as string })

  return (
    <>
      <Head>
        <title>Note</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        {!note.data ? 'death' : note.data.title}
      </Layout>
    </>
  )
}

export default withAuth(NotePage)
