import { createId } from '@paralleldrive/cuid2'
import { type NextPage } from 'next'
import Head from 'next/head'
import type { FormEvent } from 'react'
import { useRef, useState } from 'react'
import { api } from '../../utils/api'
import { Layout } from './_layout'
import { withAuth } from './_withAuth'

const NotePage: NextPage = () => {
  const [title, setTitle] = useState('')
  const [content, setContent] = useState('')
  const utils = api.useContext()
  const create = api.note.create.useMutation({
    async onMutate (newNote) {
      await utils.note.getAll.cancel()
      const prevData = utils.note.getAll.getData()

      utils.note.getAll.setData(
        undefined,
        (old) => old ? ([...old, newNote] as typeof old) : []
      )

      return { prevData }
    },
    onError (_err, _newNote, ctx) {
      utils.note.getAll.setData(undefined, ctx?.prevData)
    },
    onSettled () {
      void utils.note.getAll.invalidate()
    }
  })
  const createNote = (evt: FormEvent<unknown>) => {
    evt.preventDefault()

    if (!title || !content) return

    create.mutate({ id: createId(), title, content })
    setTitle('')
    setContent('')
  }
  return (
    <>
      <Head>
        <title>Create New Note</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <div className="p-4 max-w-5xl w-full">
          <form className="flex flex-col gap-4"
            onSubmit={(evt) => createNote(evt)}
          >
            <div className='flex gap-4'>
              <input
                type="text"
                name="title"
                id="title"
                value={title}
                onChange={(e) => setTitle(e.target.value)}
                className="flex-1 border-b border-gray-300 outline-none"
                placeholder='Title'
              />
              <button type="submit">save</button>
            </div>
            <Editable
              className="flex-1 border-b border-gray-300 outline-none min-h-min"
              onChange={(evt, value) => {
                setContent(value || '')
                console.log(value)
              }}
            />
            {/* <textarea
              name="description"
              id="description"
              value={content}
              onChange={(e) => setContent(e.target.value)}
              className="outline-none border-b border-gray-300"
            /> */}
          </form>
        </div>
      </Layout>
    </>
  )
}

type EditableProps = Omit<React.ComponentPropsWithoutRef<'div'>, 'onInput' | 'onChange'> & {
  value?: string
  onChange?: (evt: React.FormEvent<unknown>, value: string) => void
  onInput?: (evt: React.FormEvent<unknown>, value: string) => void
}

const Editable: React.FC<EditableProps> = ({ value, onChange, className }) => {
  const ref = useRef<any>()
  const val = useRef(value || '')

  return (
    <div
      ref={ref}
      className={className}
      contentEditable
      dangerouslySetInnerHTML={{ __html: val.current }}
      onInput={(e) => {
        // eslint-disable-next-line @typescript-eslint/no-unsafe-member-access
        // console.log(ref.current?.innerHTML)
        // val.current = ref.current.innerHTML
        onChange?.(e, ref.current?.innerHTML || '')
      }}
    />
  )
}

export default withAuth(NotePage)
